[package]
name = "injective-bindings"
version = "0.1.0"
authors = ["Albert Chon <albert@injectivelabs.org>"]
edition = "2018"
description = "Bindings for CosmWasm contracts to call into custom modules of Injective Core"
repository = "https://github.com/InjectiveLabs/cw-injective/tree/master/packages/bindings"
license = "Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0-beta7" }
schemars = "0.8.8"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta7" }
