[package]
description = "Procedural macro for injective-std"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "injective-std-derive"
version     = "1.13.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
cosmwasm-std = { workspace = true }
itertools    = { workspace = true }
proc-macro2  = { workspace = true }
quote        = { workspace = true }
syn          = { workspace = true }

[dev-dependencies]
cosmwasm-std = { workspace = true }
prost        = { workspace = true }
serde        = { workspace = true }
trybuild     = { workspace = true }
