[package]
description = "Procedural macro for injective-std"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "injective-std-derive"
version     = "1.13.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
cosmwasm-std = { version = "2.1.0", features = [ "stargate" ] }
itertools    = "0.10.3"
proc-macro2  = "1.0.40"
quote        = "1.0.20"
syn          = "1.0.98"

[dev-dependencies]
cosmwasm-std = { version = "2.1.0", features = [ "stargate" ] }
prost        = "0.12.4"
serde        = "1.0.142"
trybuild     = { version = "1.0.63", features = [ "diff" ] }
