# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml

on: [push, pull_request]

name: Basic

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Fix git safe.directory in container
        run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" >/home/runner/work/_temp/_github_home/.gitconfig

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.87.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run all Rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: 1.87.0
          args: --workspace --all-targets --locked
        env:
          RUST_BACKTRACE: 1
  integration:
    name: Integration Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Fix git safe.directory in container
        run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" >/home/runner/work/_temp/_github_home/.gitconfig
      - name: Install contract toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.81.0
          target: wasm32-unknown-unknown
          override: true
      - name: Compile contracts
        run: |
          for dir in contracts/*/
          do
            cd "$dir"
            RUSTFLAGS='-C link-arg=-s' cargo wasm
            cd -
          done
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.87.0
          target: wasm32-unknown-unknown
          override: true
      - name: Run all integration tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: 1.87.0
          args: --workspace --all-targets --locked --features=integration
        env:
          RUST_BACKTRACE: 1
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Fix git safe.directory in container
        run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" >/home/runner/work/_temp/_github_home/.gitconfig

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.87.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          toolchain: 1.87.0
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          toolchain: 1.87.0
          args: -- -D warnings
